"""Data models for the Evidence Gathering Phase (Phase 2).

Defines the structures for:
1. EvidencePlan: What to gather.
2. SpecialistResult: What agents return.
3. EvidencePackage: The aggregated final result.
"""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


class SpecialistType(str, Enum):
    """Available specialist agents."""
    TRANSACTION = "TransactionSpecialist"
    CUSTOMER = "CustomerSpecialist"
    SHIPPING = "ShippingSpecialist"


class EvidenceType(str, Enum):
    """Types of evidence to collect."""
    TRANSACTION_HISTORY = "TRANSACTION_HISTORY"
    DEVICE_LOGS = "DEVICE_LOGS"
    SHIPPING_DETAILS = "SHIPPING_DETAILS"
    PROOF_OF_DELIVERY = "PROOF_OF_DELIVERY"


class EvidencePlan(BaseModel):
    """Plan generated by the EvidencePlanner."""
    
    strategy: str = Field(description="Name of the strategy (e.g., 'CE_3_0_QUALIFICATION')")
    required_evidence: List[EvidenceType] = Field(description="List of evidence types to fetch")
    specialists: List[SpecialistType] = Field(description="List of specialists to invoke")


class SpecialistResult(BaseModel):
    """Base class for all specialist outputs."""
    
    specialist: SpecialistType
    success: bool = Field(description="Whether the data fetch was successful")
    error: Optional[str] = Field(None, description="Error message if failed")
    timestamp: str = Field(description="ISO timestamp of fetch")


class TransactionInfo(BaseModel):
    """Schema for a single transaction."""
    transaction_id: str
    date: str
    amount: float
    currency: str
    description: str


class TransactionEvidence(SpecialistResult):
    """Output from TransactionSpecialist."""
    
    specialist: SpecialistType = SpecialistType.TRANSACTION
    transactions: List[TransactionInfo] = Field(default_factory=list)
    total_found: int = Field(0)


class CustomerSignal(BaseModel):
    """Schema for customer data signals."""
    ip_address: Optional[str] = None
    device_id: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    shipping_address: Optional[str] = None


class CustomerEvidence(SpecialistResult):
    """Output from CustomerSpecialist."""
    
    specialist: SpecialistType = SpecialistType.CUSTOMER
    signal: Optional[CustomerSignal] = None


class ShippingEvidence(SpecialistResult):
    """Output from ShippingSpecialist."""
    
    specialist: SpecialistType = SpecialistType.SHIPPING
    carrier: Optional[str] = None
    tracking_number: Optional[str] = None
    status: Optional[str] = None
    delivered_date: Optional[str] = None
    pod_signature_url: Optional[str] = None
    pod_image_url: Optional[str] = None
    delivery_address: Optional[str] = None


class CE3QualificationResult(BaseModel):
    """Result of the CE 3.0 eligibility check."""
    
    qualified: bool
    reason: str
    prior_transaction_count: int
    matching_signal_count: int
    matched_signals: List[str] = Field(default_factory=list, description="List of matched fields (e.g. ['IP', 'Device'])")


class EvidencePackage(BaseModel):
    """Final aggregated package returned by Phase 2."""
    
    dispute_id: str
    reason_code: str
    plan: EvidencePlan
    
    # Evidence Containers
    transaction_evidence: Optional[TransactionEvidence] = None
    customer_evidence: Optional[CustomerEvidence] = None
    shipping_evidence: Optional[ShippingEvidence] = None
    
    # Validation Results
    ce3_result: Optional[CE3QualificationResult] = None
    
    # Metadata
    completeness_score: float = Field(ge=0.0, le=1.0)
    gathered_at: str

